export const CHAMPIONS_GET_TYPES = 'CHAMPIONS_GET_TYPES'
export const CHAMPIONS_GENERATE = 'CHAMPIONS_GENERATE'

export const PLAYER_INIT = 'PLAYER_INIT'
export const PLAYER_ADD_CHAMPION = 'PLAYER_ADD_CHAMPION'
export const PLAYER_START_SCENARIO = 'PLAYER_START_SCENARIO'
export const PLAYER_STOP_SCENARIO = 'PLAYER_STOP_SCENARIO'
export const PLAYER_CONTINUE_SCENARIO = 'PLAYER_CONTINUE_SCENARIO'
export const PLAYER_SAVE = 'PLAYER_SAVE'

export const GAME_TIME_START = 'GAME_TIME_START'
export const GAME_TIME_STOP = 'GAME_TIME_STOP'
export const GAME_TIME_SUBSCRIBE = 'GAME_TIME_SUBSCRIBE'
export const GAME_TIME_UNSUBSCRIBE = 'GAME_TIME_UNSUBSCRIBE'